### ISSUE TITLE
Work on inverter today?

### ISSUE THREAD

**Issue by wangzeyi** [Alexanderallenbrown/MotionBase#16]
Hello Professor @Alexanderallenbrown :

Shall we work on the inverter today?

@macjones743 @dallisg711

**Comment by Alexanderallenbrown** [comment]
Hey Andy

You can work on it if you wish. Please send me an email when you are ready to plug it in for the first time so I can drop by and check the wiring.

**Comment by wangzeyi** [comment]
Hello professor @Alexanderallenbrown:

There are three wires from the source, and the inverter only takes two wires, how do we do that?

**Comment by Alexanderallenbrown** [comment]
There are two screws on the bottom of the case that are for the green ground wire. This is true of both the  motor and the source cable.

**Comment by wangzeyi** [comment]
@macjones743  the code is fixed! I made a terrible mistake.

Want to connect the arduino to the inverter to test the code, and work on position control?

**Comment by wangzeyi** [comment]
Hello professor @Alexanderallenbrown 

I was testing our transistors, and found that one of them was not working! @macjones743 
Where can we get a good tramsistor?
