### ISSUE TITLE
Checking torque curve matlab

### ISSUE THREAD

**Issue by megantuttle** [Alexanderallenbrown/MotionBase#7]
@wangzeyi @macjones743 how did you choose the values for the gains in the simulation?

**Comment by wangzeyi** [comment]
@megantuttle The accelerations are in g, so we multiply the acc by 10. Then, we only tilts for 15deg, and the max acc we get from that is sin(15), which is around 0.25g as opposed to g. So then we multiply the acc by 0.25

**Comment by wangzeyi** [comment]
prof brown said that the max acc in an actual car is g, and we can only give 0.25g, so we need to scale all the acc by 0.25

**Comment by wangzeyi** [comment]
so multiply by 10, then multiply by 0.25
